### ISSUE TITLE
zsh: command not found: m-rcfg

### ISSUE THREAD

**Issue by okinawaa** [minsoo-web/react-component-folder-generator#2]
hey minsoo thanks for making cool library

but i got error when i try to m-rcfg command after install this library
![Screen Shot 2022-03-24 at 4 40 37 PM](https://user-images.githubusercontent.com/69495129/159866515-2fbeba15-5eae-490c-956c-294bcac00191.png)

**Comment by okinawaa** [comment]
기존 명령어였던 m-rcg 는 zsh 오류는 안나오는데 작동은안됩니당 
m-rcg sad 하니
![Screen Shot 2022-03-25 at 12 17 56 AM](https://user-images.githubusercontent.com/69495129/159949521-f0d47b78-adb1-4c72-b4c9-ee5cda9c6d1d.png)
라고 나옵니당

**Comment by okinawaa** [comment]
fixed by fd8df6187aa6c578b059bbc52e8c5cd27803294b

thanks minsoo

**Comment by minsoo-web** [comment]
> fixed by [fd8df61](https://github.com/minsoo-web/react-component-folder-generator/commit/fd8df6187aa6c578b059bbc52e8c5cd27803294b)
> 
> thanks minsoo

YeaH, Thx @ChanhyukPark-Tech 👍
